# Generated by Django 4.2.7 on 2023-11-14 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Last_Name', models.CharField(max_length=255)),
                ('First_Name', models.CharField(max_length=255)),
                ('Middle_Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
                ('Year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('Department', models.CharField(choices=[('аграрного менеджменту', 'Аграрного менеджменту'), ('економіки', 'Економіки'), ('інформаційних технологій', 'Інформаційних технологій')], max_length=50)),
                ('Group_Name', models.CharField(max_length=10)),
                ('Class_Representative', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('Subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Hours_Per_Semester', models.IntegerField()),
                ('Semesters', models.IntegerField()),
                ('Taught_Over', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('Exam_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Exam_Date', models.DateField()),
                ('Grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_project_name.students')),
                ('Subject_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_project_name.subjects')),
            ],
        ),
    ]
